function caseData = buildCaseStruct(caseName, expdata, output, DRate, color, ne, pe, co, am, sd, itf, ctrl)

    getTime = @(states) cellfun(@(s) s.time, states);
    getE = @(states) cellfun(@(s) s.(ctrl).E, states);

    states = output.states;
    model = output.model;

    time_s = getTime(states);
    sim_voltage_v = getE(states);
    exp_capacity_ah = expdata.time * expdata.I / hour;
    sim_capacity_ah = time_s * expdata.I / hour;

    cmax_ne = model.(ne).(co).(am).(itf).saturationConcentration;
    cmax_pe = model.(pe).(co).(am).(itf).saturationConcentration;

    caseData = struct( ...
        'case_name'               , caseName, ...
        'current_a'               , expdata.I, ...
        'drate'                   , DRate, ...
        'color'                   , color, ...
        'experimental_voltage_v'  , expdata.U(:)', ...
        'sim_voltage_v'           , sim_voltage_v(:)', ...
        'exp_capacity_ah'         , exp_capacity_ah(:)', ...
        'sim_capacity_ah'         , sim_capacity_ah(:)', ...
        'time_h'                  , time_s(:)' / hour, ...
        'x_elyte_um'              , getSpatialCoordinate(model.Electrolyte.G) * 1e6, ...
        'x_ne_um'                 , getSpatialCoordinate(model.(ne).(co).G) * 1e6, ...
        'x_pe_um'                 , getSpatialCoordinate(model.(pe).(co).G) * 1e6, ...
        'elyte_c'                 , stackStateVectors(states, @(s) s.Electrolyte.c(:)), ...
        'elyte_phi'               , stackStateVectors(states, @(s) s.Electrolyte.phi(:)), ...
        'ne_phi'                  , stackStateVectors(states, @(s) s.(ne).(co).phi(:)), ...
        'pe_phi'                  , stackStateVectors(states, @(s) s.(pe).(co).phi(:)), ...
        'ne_theta'                , stackStateVectors(states, @(s) s.(ne).(co).(am).(sd).cSurface(:)) ./ cmax_ne, ...
        'pe_theta'                , stackStateVectors(states, @(s) s.(pe).(co).(am).(sd).cSurface(:)) ./ cmax_pe);

end
