function out = caseToJsonStruct(caseData)

    out = struct( ...
        'case_name', caseData.case_name, ...
        'current_a', caseData.current_a, ...
        'drate', caseData.drate, ...
        'experimental_voltage_v', caseData.experimental_voltage_v, ...
        'sim_voltage_v', caseData.sim_voltage_v, ...
        'exp_capacity_ah', caseData.exp_capacity_ah, ...
        'sim_capacity_ah', caseData.sim_capacity_ah, ...
        'time_h', caseData.time_h, ...
        'x_elyte_um', caseData.x_elyte_um, ...
        'x_ne_um', caseData.x_ne_um, ...
        'x_pe_um', caseData.x_pe_um, ...
        'elyte_c', caseData.elyte_c, ...
        'elyte_phi', caseData.elyte_phi, ...
        'ne_phi', caseData.ne_phi, ...
        'pe_phi', caseData.pe_phi, ...
        'ne_theta', caseData.ne_theta, ...
        'pe_theta', caseData.pe_theta);

end
