function shortPath = getShortParameterPath(path)

    % Handy short names
    ne       = 'NegativeElectrode';
    pe       = 'PositiveElectrode';
    elyte    = 'Electrolyte';
    am       = 'ActiveMaterial';
    itf      = 'Interface';
    sd       = 'SolidDiffusion';
    ctrl     = 'Control';
    co       = 'Coating';
    bd       = 'Binder';
    ca       = 'ConductingAdditive';
    cc       = 'CurrentCollector';
    sep      = 'Separator';
    geom     = 'Geometry';
    rbc      = 'regionBruggemanCoefficients';
    vf       = 'volumeFraction';
    theta0   = 'guestStoichiometry0';
    theta100 = 'guestStoichiometry100';
    D        = 'referenceDiffusionCoefficient';
    vsa      = 'volumetricSurfaceArea';

    fieldShortNames = struct(ne      , 'ne'      , ...
                             pe      , 'pe'      , ...
                             elyte   , 'elyte'   , ...
                             am      , 'am'      , ...
                             itf     , 'itf'     , ...
                             sd      , 'sd'      , ...
                             ctrl    , 'ctrl'    , ...
                             co      , 'co'      , ...
                             bd      , 'bd'      , ...
                             ca      , 'ca'      , ...
                             cc      , 'cc'      , ...
                             sep     , 'sep'     , ...
                             geom    , 'geom'    , ...
                             rbc     , 'rbc'     , ...
                             vf      , 'vf'      , ...
                             theta0  , 'theta0'  , ...
                             theta100, 'theta100', ...
                             D       , 'D'       , ...
                             vsa     , 'vsa');

    shortPathParts = path;

    for ipart = 1:numel(path)
        field = path{ipart};
        if isfield(fieldShortNames, field)
            shortPathParts{ipart} = fieldShortNames.(field);
        end
    end

    shortPath = strjoin(shortPathParts, '.');

end
