clear all
close all


ne    = 'NegativeElectrode';
pe    = 'PositiveElectrode';
elyte = 'Electrolyte';
sep   = 'Separator';
ctrl  = 'Control';

getTime = @(states) cellfun(@(state) state.time, states);
getE = @(states) cellfun(@(state) state.(ctrl).E, states);

geometry = '1d';
groupingStrategy = 'hybrid_adaptive';
useRegionBruggemanCoefficients = true;
runFiniteDifferenceValidation = false;
finiteDifferencePerturbationSize = 1e-7;

datafilename = fullfile(getHydra0Dir(), 'raw-data', 'TE_1473.mat');
saveddata    = load(datafilename);
dataraw      = saveddata.experiment;

% Highest DRate is last
expdata = struct('time', dataraw.time{end} * hour        , ...
                 'U'   , dataraw.voltage{end}            , ...
                 'E'   , dataraw.voltage{end}            , ...
                 'cap' , abs(trapz(dataraw.time{end}*hour, dataraw.current{end})), ...
                 'I'   , abs(mean(dataraw.current{end})), ...
                 'rawI', dataraw.current{end});
expdata.DRate = expdata.I / expdata.cap * hour;

jsonstructBase = parseBattmoJson(fullfile(getHydra0Dir(), 'parameters', 'h0b-base.json'));
% jsonstructBase.(ctrl).useCVswitch = true;
jsonstructBase.(elyte).useRegionBruggemanCoefficients = useRegionBruggemanCoefficients;

if useRegionBruggemanCoefficients
    jsonstructBase.(elyte).regionBruggemanCoefficients = struct(ne, 1.5, sep, 1.5, pe, 1.5);
    % shortnames = { ...
    %     'ne_vsa', 'pe_vsa', 'ne_bg', 'pe_bg', ...
    %     'ne_D', 'pe_D', ... %'ne_j0', 'pe_j0', ...
    %     'elyte_bg_ne', 'elyte_bg_pe', 'elyte_bg_sep'};

    shortnames = {'ne_vsa', 'pe_vsa', 'ne_D', 'pe_D', 'elyte_bgfactor'};

else
    shortnames = {'ne_vsa', 'pe_vsa', 'ne_D', 'pe_D', 'elyte_bg'};
end

jsonstructStart = parseBattmoJson(fullfile( ...
    getHydra0Dir(), 'parameters', 'equilibrium-calibration-parameters.json'));
jsonstructCurrent = mergeStructs({jsonstructStart, jsonstructBase});

simulationInput = struct( ...
    'I', expdata.I, ...
    'totalTime', expdata.time(end), ...
    'geometry', geometry, ...
    'highRateParams', jsonstructCurrent);
output = runHydra(simulationInput, 'clearSimulation', false);

figure; plot(getTime(output.states)/hour, getE(output.states)); hold on; grid on
plot(expdata.time/hour, expdata.E, 'k--');

fprintf('Sim time end %g h\n', output.states{end}.time/hour);
fprintf('Exp time end %g h\n', expdata.time(end)/hour);
%return

% if output.states{end}.time > expdata.time(end)
%     index = find(getTime(output.states) <= expdata.time(end), 1, 'last');
%     output.states = output.states(1:index);
% end

parameterSetter = ParamSetter('shortnames', shortnames, ...
                              'useRegionBruggemanCoefficients', useRegionBruggemanCoefficients);

simulationSetup = struct( ...
    'state0', output.initstate, ...
    'model', output.model, ...
    'schedule', output.schedule);
parameterSetter.validate(simulationSetup.model);

getValues = @(model, unused) parameterSetter.getValues(model);
setValues = @(model, unused, values) ...
    parameterSetter.setValues(model, values);
parameters = {
    ModelParameterScaled(simulationSetup, ...
                         'name', 'ParamSetter', ...
                         'belongsTo', 'model', ...
                         'location', {''}, ...
                         'boxLims', parameterSetter.boxLims, ...
                         'scaling', 'linear', ...
                         'shortnames', parameterSetter.shortnames, ...
                         'getfun', getValues, ...
                         'setfun', setValues)
             };

scaledParameters = getScaledParameterVector( ...
    simulationSetup, parameters);
objective = ParamOptFuncReg( ...
    expdata, parameterSetter.shortnames, ...
    simulationSetup, scaledParameters);
objectiveFunction = @(model, states, schedule, params, p, varargin) ...
    objective.leastSquaresEWithReg( ...
    model, states, schedule, params, p, varargin{:});

values = objectiveFunction( ...
    simulationSetup.model, output.states, ...
    simulationSetup.schedule, parameters, scaledParameters);
objectiveScaling = sum([values{:}]);

[objectiveValue, scaledGradient] = evalObjectiveBattmoReg( ...
    scaledParameters, objectiveFunction, simulationSetup, parameters, ...
    'gradientMethod', 'AdjointAD', ...
    'objScaling', objectiveScaling);
sensitivities = scaledGradient * objectiveScaling;
parameterValues = parameterSetter.getValues(simulationSetup.model);

objectiveValueFD = [];
scaledGradientFD = [];
sensitivitiesFD = [];
relativeError = [];

if runFiniteDifferenceValidation
    [objectiveValueFD, scaledGradientFD] = evalObjectiveBattmoReg( ...
        scaledParameters, objectiveFunction, simulationSetup, parameters, ...
        'gradientMethod', 'PerturbationADNUM', ...
        'PerturbationSize', finiteDifferencePerturbationSize, ...
        'objScaling', objectiveScaling);

    sensitivitiesFD = scaledGradientFD * objectiveScaling;
    relativeError = abs(scaledGradient - scaledGradientFD) ./ ...
                    (abs(scaledGradient) + abs(scaledGradientFD));
end

parameterGroups = createClusteredParameterGroups( ...
    parameterSetter.shortnames, sensitivities, groupingStrategy, 3);

fprintf('\nMATLAB sensitivities used for grouping:\n');
for index = 1:numel(parameterSetter.shortnames)
    fprintf('  %-12s: % .8e\n', ...
            parameterSetter.shortnames{index}, sensitivities(index));
end

% Plot sensitivities
figure;
bar(abs(sensitivities));
set(gca, 'XTick', 1:numel(parameterSetter.shortnames), ...
         'XTickLabel', strrep(parameterSetter.shortnames, '_', '\_'), ...
         'XTickLabelRotation', 45);
ylabel('Sensitivity');
title('Sensitivities of Parameters');

if runFiniteDifferenceValidation
    disp(table(parameterSetter.shortnames, parameterValues, sensitivities, sensitivitiesFD, relativeError, ...
               'VariableNames', {'Shortname', 'ParameterValue', 'AdjointSensitivity', ...
                                 'FiniteDifferenceSensitivity', 'RelativeError'}));
    fprintf('Finite-difference perturbation size in scaled coordinates: %.3e\n', ...
            finiteDifferencePerturbationSize);
    fprintf('Objective values: adjoint %.16e, finite-difference %.16e\n', ...
            objectiveValue, objectiveValueFD);
else
    disp(table(parameterSetter.shortnames, parameterValues, sensitivities, ...
               'VariableNames', {'Shortname', 'ParameterValue', 'AdjointSensitivity'}));
    fprintf('Objective values: adjoint %.16e\n', objectiveValue);
end

result = struct( ...
    'shortnames', {parameterSetter.shortnames}, ...
    'sensitivities', sensitivities, ...
    'sensitivitiesFD', sensitivitiesFD, ...
    'scaledGradient', scaledGradient, ...
    'scaledGradientFD', scaledGradientFD, ...
    'relativeError', relativeError, ...
    'parameterValues', parameterValues, ...
    'objectiveValue', objectiveValue, ...
    'objectiveValueFD', objectiveValueFD, ...
    'objectiveScaling', objectiveScaling, ...
    'scaledParameters', scaledParameters, ...
    'runFiniteDifferenceValidation', runFiniteDifferenceValidation, ...
    'finiteDifferencePerturbationSize', finiteDifferencePerturbationSize, ...
    'parameterGroups', {parameterGroups}, ...
    'useRegionBruggemanCoefficients', ...
    useRegionBruggemanCoefficients);
