from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PARAMETERS_DIR = ROOT / "parameters"
PUBLICATION_FIGURES_DIR = ROOT / "figures" / "publication"

PUBLICATION_PREFIX = "INP5-70-120-H0B_graphite-lnmo_schmitt-2026"

PUBLICATION_BPX_FILENAME = f"{PUBLICATION_PREFIX}_validation.bpx.json"
PUBLICATION_BPX_PATH = PARAMETERS_DIR / PUBLICATION_BPX_FILENAME

PUBLICATION_BATTMO_EXPERIMENT_BASENAME = f"{PUBLICATION_PREFIX}_battmo-vs-experiment"
PUBLICATION_BATTMO_EXPERIMENT_FIGURE_PATH = PUBLICATION_FIGURES_DIR / f"{PUBLICATION_BATTMO_EXPERIMENT_BASENAME}.png"
PUBLICATION_BATTMO_EXPERIMENT_SUMMARY_PATH = PUBLICATION_FIGURES_DIR / f"{PUBLICATION_BATTMO_EXPERIMENT_BASENAME}-summary.json"
