%% Adjoint sensitivities of EQC and HRC parameters at the current extremes
%
% This script evaluates the four independent equilibrium-calibration (EQC)
% parameters and the five selected high-rate-calibration (HRC) parameters
% at the lowest- and highest-current experiments. Adjoint gradients are
% reported by computeSensitivities and independently checked with finite
% differences in the same scaled parameter coordinates.

clearvars
close all

repoRoot = getHydra0Dir();
ctrl = 'Control';
getTime = @(states) cellfun(@(s) s.time, states);

numTimesteps = 100;
finiteDifferenceStep = 1e-7;
shortnames = {'ne_vsa', 'pe_vsa', 'ne_D', 'pe_D', ...
              'elyte_bgfactor'};
useRegionBruggemanCoefficients = true;

filename = fullfile(getHydra0Dir(), 'parameters', ...
                    'equilibrium-calibration-parameters.json');
jsonstructEC = parseBattmoJson(filename);

filename = fullfile(getHydra0Dir(), 'parameters', ...
                    'high-rate-calibration-parameters.json');
jsonstructHRC = parseBattmoJson(filename);

datafilename = fullfile(getHydra0Dir(), 'raw-data', 'TE_1473.mat');
saveddata = load(datafilename);
dataraw = saveddata.experiment;

numberOfExperiments = numel(dataraw.time);
assert(numberOfExperiments >= 2, ...
       'At least two rate experiments are required.');
% The experimental data is ordered from lowest rate to highest rate.
conditionIndices = [1, numberOfExperiments];

results = cell(1, numel(conditionIndices));
summaryTables = cell(2 * numel(conditionIndices), 1);
tableIndex = 0;

for conditionNumber = 1:numel(conditionIndices)
    dataIndex = conditionIndices(conditionNumber);

    expdata = struct('time', dataraw.time{dataIndex} * hour, ...
                     'U'   , dataraw.voltage{dataIndex}    , ...
                     'I'   , abs(mean(dataraw.current{dataIndex})));

    % Use the measured current rather than Control.DRate. An EQC volume-
    % fraction perturbation changes the model capacity; D-rate control
    % would therefore change the applied current at the same time. Fixing
    % I isolates the response to the calibrated parameter at this test
    % condition.
    input0 = struct( ...
        'I', expdata.I, ...
        'totalTime', expdata.time(end), ...
        'numTimesteps', numTimesteps, ...
        'lowRateParams', jsonstructEC, ...
        'highRateParams', jsonstructHRC, ...
        'useRegionBruggemanCoefficients', ...
            useRegionBruggemanCoefficients, ...
        'include_current_collectors', true);

    output0 = runHydra(input0, 'clearSimulation', false);

    % Use a fixed schedule for consistency between the forward solve,
    % discrete adjoint, and finite-difference simulations.
    output0.nls.timeStepSelector = SimpleTimeStepSelector();
    output0.nls.maxTimestepCuts = 0;

    % Evaluate experimental data at simulation times.
    simtimes = getTime(output0.states);
    assert(expdata.time(1) <= simtimes(1));
    assert(abs(expdata.time(end) - simtimes(end))/simtimes(end) < 1e-11);

    Evals = interp1(expdata.time, expdata.U, simtimes, ...
                    'linear', 'extrap');
    statesExp = cell(numel(output0.states), 1);

    for stepIndex = 1:numel(output0.states)
        statesExp{stepIndex}.time = simtimes(stepIndex);
        statesExp{stepIndex}.(ctrl).E = Evals(stepIndex);
    end

    simulatorSetup = SimulationSetup(struct( ...
        'model', output0.model, ...
        'schedule', output0.schedule, ...
        'initstate', output0.initstate, ...
        'NonLinearSolver', output0.nls, ...
        'OutputMinisteps', false));

    % Division by duration makes this a time-averaged squared voltage
    % error, so the long low-rate experiment is comparable to the shorter
    % high-rate experiment.
    lsq = @(simsetup, states, varargin) leastSquaresEI( ...
        simsetup, states, statesExp, ...
        'scaling', expdata.time(end), varargin{:});
    v = lsq(simulatorSetup, output0.states);
    scaling = sum(vertcat(v{:}));
    assert(isfinite(scaling) && scaling > 0, ...
           'The baseline objective scaling must be finite and positive.');

    conditionResult = struct( ...
        'current', expdata.I, ...
        'duration', expdata.time(end), ...
        'objectiveScaling', scaling);

    % EQC: theta100 and total active-material amount for each electrode.
    % The custom ModelParameter implementation maintains the derived
    % theta0 values, all coupled model fields, and the initial state when
    % these coordinates are seeded for AD or perturbed for finite
    % differences.
    EQC = EquilibriumCalibrationSensitivity(simulatorSetup);
    [eqcReport, eqcFD, eqcValues] = evaluateParameterSet( ...
        simulatorSetup, EQC.getParams(), EQC.shortnames, lsq, ...
        scaling, finiteDifferenceStep, ...
        sprintf('Current %.6g A: EQC', expdata.I));
    conditionResult.EQC = struct( ...
        'parameterValues', eqcValues, ...
        'adjoint', eqcReport, ...
        'finiteDifference', eqcFD);

    tableIndex = tableIndex + 1;
    summaryTables{tableIndex} = makeSummaryTable( ...
        conditionResult, 'EQC', eqcReport, eqcFD);

    % HRC: use the same adjoint machinery and calibrated model at the same
    % experimental current and duration.
    HRC = HighRateCalibration(simulatorSetup, ...
                              'shortnames', shortnames);
    [hrcReport, hrcFD, hrcValues] = evaluateParameterSet( ...
        simulatorSetup, HRC.getParams(), HRC.shortnames, lsq, ...
        scaling, finiteDifferenceStep, ...
        sprintf('Current %.6g A: HRC', expdata.I));
    conditionResult.HRC = struct( ...
        'parameterValues', hrcValues, ...
        'adjoint', hrcReport, ...
        'finiteDifference', hrcFD);

    tableIndex = tableIndex + 1;
    summaryTables{tableIndex} = makeSummaryTable( ...
        conditionResult, 'HRC', hrcReport, hrcFD);

    results{conditionNumber} = conditionResult;
end

sensitivityTable = vertcat(summaryTables{:});
disp(sensitivityTable);

% outputDirectory = fullfile(repoRoot, 'scripts', ...
%                            'calibration-sensitivities');
% save(fullfile(outputDirectory, 'calibration-sensitivities.mat'), ...
%      'results', 'sensitivityTable');
% writetable(sensitivityTable, fullfile( ...
%     outputDirectory, 'calibration-sensitivities.csv'));


function [report, finiteDifference, initialParameterValues] = ...
        evaluateParameterSet(simulatorSetup, parameters, shortnames, ...
                             lsq, scaling, ...
                             finiteDifferenceStep, heading)

    X0 = getScaledParameterVector(simulatorSetup, parameters);
    initialParameterValues = cellfun( ...
        @(parameter) parameter.getParameterValue(simulatorSetup), parameters);

    objective = @(p, varargin) evalObjectiveBattmo( ...
        p, lsq, simulatorSetup, parameters, ...
        'objScaling', scaling, varargin{:});
    objectiveAdjoint = @(p) objective( ...
        p, 'gradientMethod', 'AdjointAD');

    report = computeSensitivities( ...
        X0, objectiveAdjoint, shortnames, scaling, 'heading', heading);
    [~, finiteDifference] = compareAdjointAndFiniteDifferenceGradients( ...
        X0, objective, shortnames, ...
        'adjointGradient', report.scaledGradient, ...
        'PerturbationSize', finiteDifferenceStep);

    fprintf('  finite-difference validation: %d/%d within tolerance\n', ...
            nnz(finiteDifference.passed), ...
            numel(finiteDifference.passed));
    assert(all(finiteDifference.relativeError(:) <= ...
               finiteDifference.relativeTolerance), ...
           ['Finite-difference validation failed: relative gradient ', ...
            'error exceeds the tolerance of %g.'], ...
           finiteDifference.relativeTolerance);

end


function tableOutput = makeSummaryTable( ...
        condition, parameterSet, report, finiteDifference)

    numberOfParameters = numel(report.shortnames);
    averageSquaredVoltageError = ...
        report.objectiveValue .* condition.objectiveScaling;
    finiteDifferenceSensitivity = ...
        finiteDifference.finiteDifferenceGradient .* ...
        condition.objectiveScaling;

    tableOutput = table( ...
        repmat(condition.current, numberOfParameters, 1), ...
        repmat(condition.duration / hour, numberOfParameters, 1), ...
        repmat({parameterSet}, numberOfParameters, 1), ...
        report.shortnames, ...
        repmat(averageSquaredVoltageError, numberOfParameters, 1), ...
        report.sensitivities, ...
        finiteDifferenceSensitivity, ...
        finiteDifference.relativeError, ...
        finiteDifference.passed, ...
        finiteDifference.scheme, ...
        report.initialGroup, ...
        'VariableNames', { ...
            'Current_A', 'Duration_h', 'ParameterSet', 'Parameter', ...
            'AverageSquaredVoltageError_V2', ...
            'AdjointSensitivity_V2', ...
            'FiniteDifferenceSensitivity_V2', ...
            'RelativeGradientError', 'GradientCheckPassed', ...
            'FiniteDifferenceScheme', 'SensitivityClass'});

end
